name: CI

on:
  push:
    branches: [master, develop, feature/*, renovate/*, release/*]
  pull_request:
    branches: [master, develop, feature/*, renovate/*, release/*]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --prod
      - name: Test
        run: npm test
      - name: E2E
        run: |
          npx webdriver-manager update --versions.chrome=87.0.4280.88
          npm run e2e:ci
  documentation:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Generate documentation
        run: npm run compodoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: documentation
          clean: true
