name: CI

on:
  push:
    branches: [master, develop, feature/*, renovate/*]
  pull_request:
    branches: [master, develop, feature/*, renovate/*]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Build
        run: npm run build -- --prod
      - name: Test
        run: npm test
      - name: E2E
        run: npm run e2e
  documentation:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - name: Generate documentation
        run: npm run build compdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: documentation
          CLEAN: true
